"use strict";

Object.defineProperty(exports, "__esModule", {
	value: true
});
var HEADER_BUTTON_CLICK = exports.HEADER_BUTTON_CLICK = "HEADER_BUTTON_CLICK";
var HEADER_CLICK = exports.HEADER_CLICK = "HEADER_CLICK";
var ROW_BUTTON_CLICK = exports.ROW_BUTTON_CLICK = "ROW_BUTTON_CLICK";
var ROW_CLICK = exports.ROW_CLICK = "ROW_CLICK";
var FILTER_BUTTON_CLICK = exports.FILTER_BUTTON_CLICK = "FILTER_BUTTON_CLICK";
var CLEAR_FILTER_BUTTON_CLICK = exports.CLEAR_FILTER_BUTTON_CLICK = "CLEAR_FILTER_BUTTON_CLICK";
var PREV_PAGE = exports.PREV_PAGE = "PREV_PAGE";
var NEXT_PAGE = exports.NEXT_PAGE = "NEXT_PAGE";
var GOTO_PAGE = exports.GOTO_PAGE = "GOTO_PAGE";
var SET_PAGE_SIZE = exports.SET_PAGE_SIZE = "SET_PAGE_SIZE";
var SELECT_MENU_ITEM = exports.SELECT_MENU_ITEM = "SELECT_MENU_ITEM";

exports.default = {
	HEADER_BUTTON_CLICK: HEADER_BUTTON_CLICK,
	HEADER_CLICK: HEADER_CLICK,
	ROW_BUTTON_CLICK: ROW_BUTTON_CLICK,
	ROW_CLICK: ROW_CLICK,
	FILTER_BUTTON_CLICK: FILTER_BUTTON_CLICK,
	CLEAR_FILTER_BUTTON_CLICK: CLEAR_FILTER_BUTTON_CLICK,
	PREV_PAGE: PREV_PAGE,
	NEXT_PAGE: NEXT_PAGE,
	GOTO_PAGE: GOTO_PAGE,
	SET_PAGE_SIZE: SET_PAGE_SIZE,
	SELECT_MENU_ITEM: SELECT_MENU_ITEM
};