export const HEADER_BUTTON_CLICK = 'HEADER_BUTTON_CLICK';
export const HEADER_CLICK = 'HEADER_CLICK';
export const ROW_BUTTON_CLICK = 'ROW_BUTTON_CLICK';
export const ROW_CLICK = 'ROW_CLICK';
export const FILTER_BUTTON_CLICK = 'FILTER_BUTTON_CLICK';
export const CLEAR_FILTER_BUTTON_CLICK = 'CLEAR_FILTER_BUTTON_CLICK';
export const PREV_PAGE = 'PREV_PAGE';
export const NEXT_PAGE = 'NEXT_PAGE';
export const GOTO_PAGE = 'GOTO_PAGE';
export const SET_PAGE_SIZE = 'SET_PAGE_SIZE';
export const SELECT_MENU_ITEM = 'SELECT_MENU_ITEM';

export default {
	HEADER_BUTTON_CLICK,
	HEADER_CLICK,
	ROW_BUTTON_CLICK,
	ROW_CLICK,
	FILTER_BUTTON_CLICK,
	CLEAR_FILTER_BUTTON_CLICK,
	PREV_PAGE,
	NEXT_PAGE,
	GOTO_PAGE,
	SET_PAGE_SIZE,
	SELECT_MENU_ITEM
};
